# This is a basic workflow to trigger to meal planner generation
name:
  Meal Planner Job

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
  
  # # Triggers the workflow 3 am every Saturdyy
  # schedule:
  #   - cron: "0 3 * * 6" 

env:
  prod: ${{ secrets.EMAIL_PASSWORD }}
  prod: ${{ secrets.EMAIL_USERNAME }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Ensure code is checked out

    - name: Set up Python
      uses: actions/setup-python@v4  # Use the latest version of setup-python
      with:
        python-version: '3.10.16'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: List files in the repository (recursive)
      run: |
        ls -alR  # Lists all files to check the directory structure

    - name: Run unit tests
      run: |
        python App/meal_planner_email.py # If the file is in the root directory
