# This is a basic workflow to trigger unit testing
name:
  Test before PR

# Controls when the workflow will run
on:
  # Triggers the workflow when a PR is detected
  pull_request:
    branches: 
        - main


jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
