name: Test before PR

on:
  pull_request:
    branches:
      - main

env:
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
  PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4  # Use the latest stable version
      with:
        python-version: '3.11.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: List files in current directory
      run: |
        ls -al

    - name: Debugging path issues (recursive)
      run: |
        ls -alR

    - name: Run unit tests
      run: |
        python hello_world.py
